Hello World

diff --git a/python-hello_world/101-compile b/python-hello_world/101-compile
--- a/python-hello_world/101-compile
+++ b/python-hello_world/101-compile
@@ -1,4 +1,8 @@
 #!/bin/bash
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not set."
+    exit 1
+fi
 python -m py_compile "$PYFILE"
 compiled_file="${PYFILE}c"
 mv "${PYFILE}c" "$compiled_file"
